# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d2776822ef725843f6e6d0f1c10ba80a93121896eea8c2b87a212057a469456490aff1464d0abc70b3e5b9134504cf33d80570c63981fa0cdc8e00d49ef263

test:
  secret_key_base: 86ed5268890c6a2bad9351616a5ee82b3a265b2f80121038229f2f7edf6a68886bb84449daf34fe7cbac9b08f1461b1422f89e402ff99cf53966bd9d098a3c18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
